DownloadDatasets <- function(){
  #CARGA DE FUNCIONES
  # GISD downloaded online
  # CABI downloaded online
  source(file.path("R","Jellyfish_Download_and_Depurate.r")) #To download online databases
  source(file.path("R", "HORUS_Download_and_Depurate.r"))
  source(file.path("R", "FirstRecords_Download_and_Depurate.r"))
  source(file.path("R", "CHILE_Download_and_Depurate.r"))
  source(file.path("R", "HORIZONSCANNINGEUROPE_Download_and_Depurate.r"))
  source(file.path("R", "CEEEI_Download_and_Depurate.r"))
  source(file.path("R", "USGS_Download_and_Depurate.r"))
  source(file.path("R", "GRIIS_Download_and_Depurate.r"))
  source(file.path("R", "Crayfish_Download_and_Depurate.r"))
  source(file.path("R", "FishBaseSeaLife_Download_and_Depurate.r"))
  source(file.path("R", "GIDIAS_Download_and_Depurate.r"))
  source(file.path("R", "FirstRecords_Download_and_Depurate.r"))
  source(file.path("R", "NISIC_Download_and_Depurate.r"))
  source(file.path("R", "GISD_Download_and_Depurate.r"))
  source(file.path("R", "CABI_Download_and_Depurate.r"))
  source(file.path("R", "AmphibiansReptilesCapinha_Download_and_Depurate.r"))
  source(file.path("R", "NonNativeFishesIndiaLohith_Download_and_Depurate.r"))
  source(file.path("R", "HORUS_Download_and_Depurate.r"))
  source(file.path("R", "Chile_Download_and_Depurate.r"))
  source(file.path("R", "CONABIO_Download_and_Depurate.r"))
  source(file.path("R", "RafaelZenni_Download_and_Depurate.r"))
  source(file.path("R", "CanoBarbacidLifeInvasaqua_Download_and_Depurate.r"))
  source(file.path("R", "JPECarboneras_Download_and_Depurate.r"))
  source(file.path("R", "FreshwaterInvasiveSpeciesInNewZealand_Download_and_Depurate.r"))
  source(file.path("R", "InvasiveSpeciesInChina_Download_and_Depurate.r"))
  source(file.path("R", "InvasiveReptilesAmphibiansFredKraus_Download_and_Depurate.r"))
  source(file.path("R", "GloNAF_Download_and_Depurate.r"))
  source(file.path("R", "InvasiveMammalsinEurope_Download_and_Depurate.r"))
  source(file.path("R", "NEOBIOTA100_Download_and_Depurate.r"))
  source(file.path("R", "BelgiumRegions_Download_and_Depurate.r"))
  source(file.path("R", "NonnativeMacrofungi_Download_and_Depurate.r"))
  source(file.path("R", "EASIN_Download_and_Depurate.r"))
  source(file.path("R", "Jellyfish_Download_and_Depurate.r"))
  source(file.path("R", "USRIIS_Download_and_Depurate.r"))
  source(file.path("R", "INVASIBER_Download_and_Depurate.r"))
  source(file.path("R", "InvaCost_Download_and_Depurate.r"))
  source(file.path("R", "GAVIA_Download_and_Depurate.r"))
  source(file.path("R", "APASD_Download_and_Depurate.r"))
  source(file.path("R", "AQUANIS_Download_and_Depurate.r"))
  source(file.path("R", "FreshwaterEcologyInfo_Download_and_Depurate.r"))
  source(file.path("R", "ArtsdataBankenNoruega_Download_and_Depurate.r"))
  source(file.path("R", "InBUyUruguay_Download_and_Depurate.r"))
  source(file.path("R", "GLANSIS_Download_and_Depurate.r"))
  source(file.path("R", "FreshwaterFishSpeciesDrainageBasins_Download_and_Depurate.r"))
  source(file.path("R", "BaseNacionalInvasorasCostaRica_Download_and_Depurate.r"))
  source(file.path("R", "InvasiveSpeciesInPortugal_Download_and_Depurate.r"))
  source(file.path("R", "GISIN_Download_and_Depurate.r"))
  source(file.path("R", "GlobalCompendiumofWeedsGCW_Download_and_Depurate.r"))
  source(file.path("R", "ListforIASManagementinJapan_Download_and_Depurate.r"))
  source(file.path("R", "ChecklistAmphipodaCrustaceaRussia_Download_and_Depurate.r"))
  source(file.path("R", "Dates_of_use_Database.r"))
  source(file.path("R", "InvasiveSpeciesSriLanka_Download_and_Depurate.r"))
  source(file.path("R", "ELNAIS_Download_and_Depurate.r"))
  source(file.path("R", "FCDFloraCroaticaDatabase_Download_and_Depurate.r"))
  source(file.path("R", "GreatBritainNSS_Download_and_Depurate.r"))
  source(file.path("R", "SwazilandsAlienPlantsDatabase_Download_and_Depurate.r"))
  source(file.path("R", "FreshwaterInvasiveMolluscs_Download_and_Depurate.r"))
  source(file.path("R", "Chen_et_All_2023_Megafauna_Download_and_Depurate.r"))
  source(file.path("R", "InvasiveVertebrateChile_Download_and_Depurate.r"))
  source(file.path("R","AlienSpeciesKyrgyzstan_Download_and_Depurate.r"))
  source(file.path("R", "DptOfConservationNewZealand_Download_and_Depurate.r"))
  source(file.path("R", "FINCA_Download_and_Depurate.r"))
  source(file.path("R", "InvasiveSpeciesOfJapan_Download_and_Depurate.r"))
  source(file.path("R", "LIBChile_Download_and_Depurate.r"))
  source(file.path("R", "BiosecurityNewZealand_Download_and_Depurate.r"))
  source(file.path("R", "AliensInCaves_Download_and_Depurate.r"))
  source(file.path("R", "HimalayanAlienAquaticFlora_Download_and_Depurate.r"))
  source(file.path("R", "NonNativeSpeciesInReservoirsBrazil_Download_and_Depurate.r"))
  source(file.path("R", "SouthAfrica2022_Download_and_Depurate.r"))
  source(file.path("R", "WeedsOfAustralia_Download_and_Depurate.r"))
  source(file.path("R", "SalmonidosChile_Download_and_Depurate.r"))
  source(file.path("R", "InvasiveSpeciesSouthAfrica_Download_and_Depurate.r"))
  source(file.path("R", "EgohetAll2020_Download_and_Depurate.r"))
  source(file.path("R", "EliasEtAll_Download_and_Depurate.r"))
  source(file.path("R", "InvasiveAquaticPlantsChile_Download_and_Depurate.r"))
  source(file.path("R", "FreshwaterFishesSingapore_Download_and_Depurate.r"))
  source(file.path("R", "AlienAnimalsSouthAfrica_Download_and_Depurate.r"))
  source(file.path("R", "NonNativeFishesIndonesia_Download_and_Depurate.r"))
  source(file.path("R", "IndonesiaAlienSpecies_Download_and_Depurate.r"))
  source(file.path("R", "NonNativeSpeciesinPoyangLakeBasin_Download_and_Depurate.r"))
  source(file.path("R", "GIATAR_Download_and_Depurate.r"))
  source(file.path("R", "WorldOfCrayfish_Download_and_Depurate.r"))
  source(file.path("R", "InvasiveSpeciesKorea_Download_and_Depurate.r"))
  source(file.path("R", "InvasiveSpeciesPhilippines_Download_and_Depurate.r"))
  source(file.path("R", "FAODIAS_Download_and_Depurate.r"))

  #EJECUCION DE FUNCIONES
  AmphibiansReptilesCapinha_Download_and_Depurate()
  CABI_Download_and_Depurate()
  CEEEI_Download_and_Depurate()
  Chile_Download_and_Depurate()
  CONABIO_Download_and_Depurate()
  FirstRecords_Download_and_Depurate()
  FishBaseSeaLife_Download_and_Depurate()
  GISD_Download_and_Depurate()
  GRIIS_Download_and_Depurate()
  HORIZONSCANNINGEUROPE_Download_and_Depurate()
  HORUS_Download_and_Depurate()
  GIDIAS_Download_and_Depurate()
  NISIC_Download_and_Depurate()
  USGS_Download_and_Depurate()
  NonNativeFishesIndiaLohith_Download_and_Depurate()
  RafaelZenni_Download_and_Depurate()
  CanoBarbacidLifeInvasaqua_Download_and_Depurate()  # Se asume que incluye ambas listas (BLACKLIST y ALERTLIST)
  Crayfish_Download_and_Depurate()
  JPECarboneras_Download_and_Depurate()
  FreshwaterInvasiveSpeciesInNewZealand_Download_and_Depurate()
  InvasiveSpeciesInChina_Download_and_Depurate()
  InvasiveReptilesAmphibiansFredKraus_Download_and_Depurate()
  GloNAF_Download_and_Depurate()
  InvasiveMammalsinEurope_Download_and_Depurate()
  NEOBIOTA100_Download_and_Depurate()
  BelgiumRegions_Download_and_Depurate()
  EASIN_Download_and_Depurate()
  Jellyfish_Download_and_Depurate()
  FreshwaterEcologyInfo_Download_and_Depurate()
  USRIIS_Download_and_Depurate()
  INVASIBER_Download_and_Depurate()
  InvaCost_Download_and_Depurate()
  GAVIA_Download_and_Depurate()
  APASD_Download_and_Depurate()
  AQUANIS_Download_and_Depurate()
  ArtsdataBankenNoruega_Download_and_Depurate()
  InBUyUruguay_Download_and_Depurate()
  GLANSIS_Download_and_Depurate()
  FreshwaterFishSpeciesDrainageBasins_Download_and_Depurate()
  BaseNacionalInvasorasCostaRica_Download_and_Depurate()
  InvasiveSpeciesInPortugal_Download_and_Depurate()
  GlobalCompendiumofWeedsGCW_Download_and_Depurate()
  GISIN_Download_and_Depurate()
  ListforIASManagementinJapan_Download_and_Depurate()
  ChecklistAmphipodaCrustaceaRussia_Download_and_Depurate()
  InvasiveSpeciesSriLanka_Download_and_Depurate()
  ELNAIS_Download_and_Depurate()
  FCDFloraCroaticaDatabase_Download_and_Depurate()
  GreatBritainNSS_Download_and_Depurate()
  SwazilandsAlienPlantsDatabase_Download_and_Depurate()
  FreshwaterInvasiveMolluscs_Download_and_Depurate()
  Chen_et_All_2023_Megafauna_Download_and_Depurate()
  InvasiveVertebrateChile_Download_and_Depurate()
  AlienSpeciesKyrgyzstan_Download_and_Depurate()
  DptOfConservationNewZealand_Download_and_Depurate()
  FINCA_Download_and_Depurate()
  InvasiveSpeciesOfJapan_Download_and_Depurate()
  LIBChile_Download_and_Depurate()
  BiosecurityNewZealand_Download_and_Depurate()
  AliensInCaves_Download_and_Depurate()
  HimalayanAlienAquaticFlora_Download_and_Depurate()
  NonNativeSpeciesInReservoirsBrazil_Download_and_Depurate()
  SouthAfrica2022_Download_and_Depurate()
  WeedsOfAustralia_Download_and_Depurate()
  SalmonidosChile_Download_and_Depurate()
  InvasiveSpeciesSouthAfrica_Download_and_Depurate()
  EgohetAll2020_Download_and_Depurate()
  EliasEtAll_Download_and_Depurate()
  InvasiveAquaticPlantsChile_Download_and_Depurate()
  FreshwaterFishesSingapore_Download_and_Depurate()
  AlienAnimalsSouthAfrica_Download_and_Depurate()
  NonNativeFishesIndonesia_Download_and_Depurate()
  IndonesiaAlienSpecies_Download_and_Depurate()
  NonNativeSpeciesinPoyangLakeBasin_Download_and_Depurate()
  GIATAR_Download_and_Depurate()
  WorldOfCrayfish_Download_and_Depurate()
  InvasiveSpeciesKorea_Download_and_Depurate()
  InvasiveSpeciesPhilippines_Download_and_Depurate()
  FAODIAS_Download_and_Depurate()

}
